theme: jekyll-theme-modernist
title: Tek Open Source
description: Tektronix Open Source Office, Using open source as a platform to connect with customers and better collaborate across internal engineering teams.
show_downloads: "false"
